export { default as Button } from './Button';
export { default as InputForm } from './InputForm';
export { default as SearchItem } from './SearchItem';
export { default as ProvinceBtn } from './ProvinceBtn';
export { default as ListPosts } from './ListPosts';
export { default as Post } from './Post';
export { default as Provinces } from './Provinces';
export { default as SlideBar } from './SlideBar';
export { default as PageNumber } from './PageNumber';
